"""Add cascade delete to PostImage

Revision ID: d35dfac8f182
Revises: 2cdbb16c6523
Create Date: 2025-02-11 13:25:56.937581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd35dfac8f182'
down_revision: Union[str, None] = '2cdbb16c6523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
